SELECT DISTINCT VICNCN.BUKRS, VICNCN.RECNNR, VICNCN.RECNTYPE, VICNCN.RECNTXT, VICNCN.INTRENO, VIBPOBJREL.PARTNER, VIBDROOCC.SWENR, BSID.BLART, BSID.BUDAT, BSID.SHKZG, BSID.DMBTR, BSID.WAERS, BSID.DMBE2, BSID.MWSKZ, BSID.MWSTS, BSID.SGTXT,
BSID.AUGDT, BSID.GJAHR, BSID.XZAHL, BUT000.BU_SORT1, BSID.VERTT, TIV2F.XMBEZ,SEMTRACFONDST.XFONDSTYP
FROM PUBLIC.VICNCN
  INNER JOIN PUBLIC.VIBDROOCC ON VICNCN.BUKRS = VIBDROOCC.OCCCNBUKRS
  AND VIBDROOCC.OCCRECNNR = VICNCN.RECNNR
  LEFT OUTER JOIN PUBLIC.VIBPOBJREL ON VICNCN.INTRENO = VIBPOBJREL.INTRENO
  LEFT OUTER JOIN PUBLIC.BUT000 ON VIBPOBJREL.PARTNER = BUT000.PARTNER
  LEFT OUTER JOIN PUBLIC.BSID ON VIBPOBJREL.PARTNER = BSID.KUNNR
  AND PUBLIC.BSID.VERTN = PUBLIC.VICNCN.RECNNR AND BSID.BUKRS = VICNCN.BUKRS
  LEFT OUTER JOIN PUBLIC.SEMTRACFONDS ON VICNCN.BUKRS = SEMTRACFONDS.FONDS
  LEFT OUTER JOIN PUBLIC.SEMTRACFONDST ON SEMTRACFONDS.FONDSTYP = SEMTRACFONDST.FONDSTYP
  LEFT OUTER JOIN PUBLIC.SEMTRACFONDS1 ON SEMTRACFONDS.FONDS = SEMTRACFONDS1.BUKRS
  LEFT OUTER JOIN PUBLIC.TIV2F ON VICNCN.RECNTYPE = TIV2F.SMVART
  WHERE PUBLIC.TIV2F.SPRAS Like 'D'
 
  
UNION ALL

SELECT DISTINCT VICNCN.BUKRS, VICNCN.RECNNR, VICNCN.RECNTYPE, VICNCN.RECNTXT, VICNCN.INTRENO, VIBPOBJREL.PARTNER, VIBDROOCC.SWENR, BSAD.BLART, BSAD.BUDAT, BSAD.SHKZG, BSAD.DMBTR, BSAD.WAERS, BSAD.DMBE2, BSAD.MWSKZ, BSAD.MWSTS, BSAD.SGTXT, 
BSAD.AUGDT, BSAD.GJAHR, BSAD.XZAHL, BUT000.BU_SORT1, BSAD.VERTT, TIV2F.XMBEZ,SEMTRACFONDST.XFONDSTYP
FROM PUBLIC.VICNCN
  INNER JOIN PUBLIC.VIBDROOCC ON VICNCN.BUKRS = VIBDROOCC.OCCCNBUKRS
  AND VIBDROOCC.OCCRECNNR = VICNCN.RECNNR
  LEFT OUTER JOIN PUBLIC.VIBPOBJREL ON VICNCN.INTRENO = VIBPOBJREL.INTRENO
  LEFT OUTER JOIN PUBLIC.BUT000 ON VIBPOBJREL.PARTNER = BUT000.PARTNER
  LEFT OUTER JOIN PUBLIC.BSAD ON VIBPOBJREL.PARTNER = BSAD.KUNNR
  AND PUBLIC.BSAD.VERTN = PUBLIC.VICNCN.RECNNR AND BSAD.BUKRS = VICNCN.BUKRS
  LEFT OUTER JOIN PUBLIC.SEMTRACFONDS ON VICNCN.BUKRS = SEMTRACFONDS.FONDS
  LEFT OUTER JOIN PUBLIC.SEMTRACFONDST ON SEMTRACFONDS.FONDSTYP = SEMTRACFONDST.FONDSTYP
  LEFT OUTER JOIN PUBLIC.SEMTRACFONDS1 ON SEMTRACFONDS.FONDS = SEMTRACFONDS1.BUKRS
  LEFT OUTER JOIN PUBLIC.TIV2F ON VICNCN.RECNTYPE = TIV2F.SMVART
  WHERE PUBLIC.TIV2F.SPRAS Like 'D'
);